server:
  port: 9001
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/resortle_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    show-sql: true
  sql:
    init:
      mode: always